### ISSUE TITLE
Skeleton UI Component Audit

### ISSUE THREAD

**Issue by lilyx13** [sait-wbdv/fall-2023#3]
Which components correlate to the features we use on the Winter 2023 site?

**DOD**: List all supported and unsupported components

**Comment by lilyx13** [comment]
A brief list of important components on Winter 2023

## Global UI Components
- Header
- MainNav
- Footer

### UI Functionality
- Pagination
- HamburgerMenuButton
- 
## Layout Components
- PostsList
  - UL that generates a list of small cards
- Schedule
  - Grouping of PostsLists
  - Color sorting
- LessonPlan

**Comment by lilyx13** [comment]
# Skeleton UI Components
- [Svelte Components](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/elements/lists)
- [Tailwind Elements](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/elements/lists)
---
## Components
- [Layout Shell](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/components/app-shell)
  - Global site layout w/side bar
- [App Bar](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/components/app-bar)
  - Use for header
- [Paginator](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/components/paginators)
  - Switch between lessons
- [Light mode toggle](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/utilities/lightswitches)
- 
### Content Components
- [Code Blocks](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/utilities/codeblocks)
- [Table of Contents](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/utilities/table-of-contents)
  - useful for quick view of lesson plan topics
  - could potentially be used with the schedule
- [Breadcumbs](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/elements/breadcrumbs)
- [Lists](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/elements/lists)
  - Potentially useful for schedule list elements
-  

### Ideas
- [Accordion](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/components/accordions)
  - Can be used to condense things like homework lists
- [Progress Bar](https://skeleton-docs-git-v2-skeleton-labs.vercel.app/components/progress-bars)
  - this or the radial could be used to indicate how far down the lesson one is

**Comment by lilyx13** [comment]
## Components that we need to make manually
- Footer
- LessonPlan

The rest seem like we could take advantage of skeleton's built in components.

**Comment by acidtone** [comment]
I'm wondering if we'll run into any issues with the source being markdown?

**Comment by lilyx13** [comment]
So far #16 is the only issue.
